"$schema" = 'https://starship.rs/config-schema.json'
add_newline = true
[character]
format = "[\\$](green bold) "

[status]
disabled = false
success_symbol = ""
format = "[$symbol$status]($style) "
style = "bold red"

[directory]
truncation_length = 3

[git_branch]
symbol = ''
format = '\([$symbol$branch(:$remote_branch)]($style)\)'

[git_status]
format = '([$all_status$ahead_behind]($style) )'
conflicted = ''
ahead = ''
behind = ''
diverged = ''
up_to_date = ''
untracked = 'ğŸ”¥'
stashed = ''
modified = 'ğŸ”¥'
staged = 'ğŸ”¥'
renamed = ''
deleted = ''
